"use client";

import { useState, useEffect } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { useTheme } from "next-themes";
import JSZip from "jszip";
import { saveAs } from "file-saver";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { TEMPLATES, Template } from "@/lib/templates";
import { NETWORKS, fetchAbiFromExplorer } from "@/lib/networks";
import { parseAbi, generateServerPy, generateRequirementsTxt, AbiItem } from "@/lib/generator";

export default function TemplatePage() {
  const params = useParams();
  const { theme, setTheme } = useTheme();
  const [template, setTemplate] = useState<Template | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    const found = TEMPLATES.find(t => t.id === params.id);
    if (found) {
      setTemplate(found);
    }
  }, [params.id]);

  const handleGenerate = async () => {
    if (!template) return;
    
    setIsGenerating(true);

    try {
      const zip = new JSZip();
      const mcpServers: Record<string, unknown> = {};
      
      const failedContracts: string[] = [];
      let successCount = 0;
      
      for (const contract of template.contracts) {
        const contractNetwork = NETWORKS.find(n => n.id === contract.network);
        if (!contractNetwork?.explorerApi) {
          failedContracts.push(`${contract.name} (no explorer API for ${contract.network})`);
          continue;
        }

        try {
          const contractAbi = await fetchAbiFromExplorer(contract.address, contractNetwork.explorerApi, contractNetwork.chainId);
          const parsedAbi = parseAbi(contractAbi) as AbiItem[];
          
          const serverName = contract.name.toLowerCase().replace(/\s+/g, "-");
          const serverPy = generateServerPy(contract.name, contract.address, contractNetwork.rpcUrl, parsedAbi);
          
          zip.file(`${serverName}/server.py`, serverPy);
          zip.file(`${serverName}/abi.json`, JSON.stringify(parsedAbi, null, 2));
          zip.file(`${serverName}/requirements.txt`, generateRequirementsTxt());
          
          mcpServers[serverName] = {
            command: "python",
            args: [`${serverName}/server.py`],
            env: {
              RPC_URL: contractNetwork.rpcUrl,
            },
          };
          successCount++;
        } catch (contractErr) {
          const errMsg = contractErr instanceof Error ? contractErr.message : "Unknown error";
          failedContracts.push(`${contract.name}: ${errMsg}`);
        }
      }

      if (successCount === 0) {
        throw new Error(`Failed to fetch ABIs. Try again in a minute.`);
      }

      if (failedContracts.length > 0) {
        toast.warning(`Some contracts failed: ${failedContracts.join(", ")}`);
      }

      const templateReadme = `# ${template.name}

${template.icon} ${template.longDescription}

## Included Contracts

${template.contracts.map(c => `- **${c.name}** (${c.address.slice(0, 10)}...): ${c.description}`).join("\n")}

## Sample Prompts

${template.samplePrompts.map(p => `- "${p}"`).join("\n")}

## Setup

1. Install dependencies for each server:
\`\`\`bash
${template.contracts.map(c => `cd ${c.name.toLowerCase().replace(/\s+/g, "-")} && pip install -r requirements.txt && cd ..`).join("\n")}
\`\`\`

2. Add to Claude Desktop config:
\`\`\`json
${JSON.stringify({ mcpServers }, null, 2)}
\`\`\`

3. Restart Claude Desktop

---
Generated by [UCAI](https://github.com/nirholas/UCAI)
`;

      zip.file("README.md", templateReadme);
      zip.file("claude_config.json", JSON.stringify({ mcpServers }, null, 2));

      const blob = await zip.generateAsync({ type: "blob" });
      saveAs(blob, `${template.id}-mcp-bundle.zip`);
      toast.success("Bundle downloaded!");
    } catch (err) {
      const message = err instanceof Error ? err.message : "Failed to generate";
      toast.error(message);
    } finally {
      setIsGenerating(false);
    }
  };

  if (!mounted) {
    return (
      <main className="min-h-screen bg-white dark:bg-slate-950">
        <div className="max-w-6xl mx-auto px-6 py-8">
          <Skeleton className="h-8 w-32 mb-8" />
          <Skeleton className="h-16 w-16 rounded-2xl mb-4" />
          <Skeleton className="h-8 w-64 mb-2" />
          <Skeleton className="h-4 w-96" />
        </div>
      </main>
    );
  }

  if (!template) {
    return (
      <main className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-slate-100 dark:from-slate-950 dark:via-slate-900 dark:to-slate-950">
        <div className="max-w-6xl mx-auto px-6 py-20 text-center">
          <h1 className="text-2xl font-bold text-slate-800 dark:text-slate-200 mb-4">Template not found</h1>
          <Link href="/"><Button>Back to Home</Button></Link>
        </div>
      </main>
    );
  }

  const relatedTemplates = TEMPLATES.filter(t => t.category === template.category && t.id !== template.id).slice(0, 3);

  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-slate-100 dark:from-slate-950 dark:via-slate-900 dark:to-slate-950">
      {/* Top Nav */}
      <div className="border-b border-slate-200 dark:border-slate-800 bg-white/80 dark:bg-slate-900/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="max-w-6xl mx-auto px-6 py-3 flex items-center justify-between">
          <Link href="/" className="text-sm text-slate-500 hover:text-slate-700 dark:hover:text-slate-300 transition-colors flex items-center gap-2">
            <span>←</span> Back to Templates
          </Link>
          <div className="flex items-center gap-3">
            <a href="https://docs.ucai.tech" target="_blank" className="text-sm text-slate-500 hover:text-slate-700 dark:hover:text-slate-300">Docs</a>
            <a href="https://github.com/nirholas/UCAI" target="_blank" className="text-sm text-slate-500 hover:text-slate-700 dark:hover:text-slate-300">GitHub</a>
            <button
              onClick={() => setTheme(theme === "dark" ? "light" : "dark")}
              className="p-2 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
            >
              {theme === "dark" ? <span>☀️</span> : <span>🌙</span>}
            </button>
          </div>
        </div>
      </div>

      <div className="max-w-6xl mx-auto px-6 py-8">
        <div className="grid grid-cols-1 lg:grid-cols-[1fr,320px] gap-8">
          {/* Main Content */}
          <div className="space-y-8">
            {/* Header */}
            <div className="flex items-start gap-5">
              <div className="w-16 h-16 rounded-2xl bg-slate-100 dark:bg-slate-800 flex items-center justify-center text-4xl shrink-0">
                {template.icon}
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-3 flex-wrap mb-2">
                  <h1 className="text-2xl font-bold text-slate-900 dark:text-slate-100">{template.name}</h1>
                  <Badge 
                    variant="outline"
                    className={
                      template.difficulty === "beginner" ? "bg-emerald-50 dark:bg-emerald-900/30 text-emerald-600 dark:text-emerald-400 border-emerald-200" :
                      template.difficulty === "intermediate" ? "bg-amber-50 dark:bg-amber-900/30 text-amber-600 dark:text-amber-400 border-amber-200" :
                      "bg-red-50 dark:bg-red-900/30 text-red-600 dark:text-red-400 border-red-200"
                    }
                  >
                    {template.difficulty}
                  </Badge>
                </div>
                <p className="text-slate-600 dark:text-slate-400">{template.description}</p>
              </div>
            </div>

            {/* Tabs */}
            <Tabs defaultValue="overview" className="w-full">
              <TabsList className="bg-slate-100 dark:bg-slate-800 p-1 rounded-lg">
                <TabsTrigger value="overview" className="data-[state=active]:bg-white dark:data-[state=active]:bg-slate-700 rounded-md">Overview</TabsTrigger>
                <TabsTrigger value="contracts" className="data-[state=active]:bg-white dark:data-[state=active]:bg-slate-700 rounded-md">Contracts</TabsTrigger>
                <TabsTrigger value="prompts" className="data-[state=active]:bg-white dark:data-[state=active]:bg-slate-700 rounded-md">Sample Prompts</TabsTrigger>
              </TabsList>

              {/* Overview Tab */}
              <TabsContent value="overview" className="mt-6 space-y-6">
                <div className="p-6 rounded-xl bg-white dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700">
                  <h3 className="text-sm font-medium text-slate-500 dark:text-slate-400 uppercase tracking-wide mb-3">About this template</h3>
                  <p className="text-slate-700 dark:text-slate-300 leading-relaxed">{template.longDescription}</p>
                </div>

                <div className="p-6 rounded-xl bg-white dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700">
                  <h3 className="text-sm font-medium text-slate-500 dark:text-slate-400 uppercase tracking-wide mb-4">Included Contracts</h3>
                  <div className="space-y-3">
                    {template.contracts.map((contract, idx) => {
                      const network = NETWORKS.find(n => n.id === contract.network);
                      return (
                        <div key={idx} className="flex items-center gap-3 p-3 rounded-lg bg-slate-50 dark:bg-slate-900/50">
                          <span className="text-lg">{network?.icon || "⬡"}</span>
                          <div className="flex-1 min-w-0">
                            <div className="font-medium text-slate-800 dark:text-slate-200">{contract.name}</div>
                            <div className="text-sm text-slate-500 dark:text-slate-400 truncate">{contract.description}</div>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              </TabsContent>

              {/* Contracts Tab */}
              <TabsContent value="contracts" className="mt-6 space-y-4">
                {template.contracts.map((contract, idx) => {
                  const network = NETWORKS.find(n => n.id === contract.network);
                  return (
                    <div key={idx} className="p-6 rounded-xl bg-white dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700">
                      <div className="flex items-start justify-between mb-4">
                        <div className="flex items-center gap-3">
                          <span className="text-2xl">{network?.icon || "⬡"}</span>
                          <div>
                            <h3 className="font-semibold text-slate-800 dark:text-slate-200">{contract.name}</h3>
                            <p className="text-sm text-slate-500 dark:text-slate-400">{network?.name || contract.network}</p>
                          </div>
                        </div>
                      </div>
                      
                      <p className="text-slate-600 dark:text-slate-400 mb-4">{contract.description}</p>
                      
                      <div className="flex items-center gap-2 p-3 rounded-lg bg-slate-50 dark:bg-slate-900/50">
                        <code className="flex-1 text-sm font-mono text-slate-600 dark:text-slate-300 truncate">
                          {contract.address}
                        </code>
                        <button
                          onClick={() => {
                            navigator.clipboard.writeText(contract.address);
                            toast.success("Copied!");
                          }}
                          className="text-sm text-slate-500 hover:text-slate-700 dark:hover:text-slate-300 shrink-0"
                        >
                          Copy
                        </button>
                      </div>
                    </div>
                  );
                })}
              </TabsContent>

              {/* Prompts Tab */}
              <TabsContent value="prompts" className="mt-6">
                <div className="p-6 rounded-xl bg-white dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700">
                  <h3 className="text-sm font-medium text-slate-500 dark:text-slate-400 uppercase tracking-wide mb-4">Try these with Claude</h3>
                  <div className="space-y-3">
                    {template.samplePrompts.map((prompt, idx) => (
                      <div 
                        key={idx}
                        className="group flex items-center justify-between p-4 rounded-lg bg-slate-50 dark:bg-slate-900/50 hover:bg-slate-100 dark:hover:bg-slate-900 transition-colors cursor-pointer"
                        onClick={() => {
                          navigator.clipboard.writeText(prompt);
                          toast.success("Prompt copied!");
                        }}
                      >
                        <p className="text-slate-700 dark:text-slate-300 italic">&ldquo;{prompt}&rdquo;</p>
                        <span className="text-xs text-slate-400 opacity-0 group-hover:opacity-100 transition-opacity">Click to copy</span>
                      </div>
                    ))}
                  </div>
                </div>
              </TabsContent>
            </Tabs>

            {/* Related Templates */}
            {relatedTemplates.length > 0 && (
              <div className="pt-8 border-t border-slate-200 dark:border-slate-800">
                <h3 className="text-sm font-medium text-slate-500 dark:text-slate-400 uppercase tracking-wide mb-4">Related Templates</h3>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                  {relatedTemplates.map((related) => (
                    <Link key={related.id} href={`/templates/${related.id}`}>
                      <div className="p-4 rounded-xl bg-white dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700 hover:border-slate-300 dark:hover:border-slate-600 transition-colors">
                        <div className="flex items-center gap-3 mb-2">
                          <span className="text-xl">{related.icon}</span>
                          <span className="font-medium text-slate-800 dark:text-slate-200 text-sm">{related.name}</span>
                        </div>
                        <p className="text-xs text-slate-500 dark:text-slate-400 line-clamp-2">{related.description}</p>
                      </div>
                    </Link>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* Sidebar */}
          <div className="space-y-6">
            {/* Install Card */}
            <div className="p-6 rounded-xl bg-white dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700 sticky top-20">
              <Button
                onClick={handleGenerate}
                disabled={isGenerating}
                size="lg"
                className="w-full bg-slate-900 hover:bg-slate-800 dark:bg-slate-100 dark:hover:bg-slate-200 dark:text-slate-900 mb-4"
              >
                {isGenerating ? "Generating..." : "Download Bundle"}
              </Button>
              <p className="text-xs text-center text-slate-500 dark:text-slate-400">
                Includes {template.contracts.length} contract{template.contracts.length > 1 ? "s" : ""} ready for Claude
              </p>
            </div>

            {/* Details Card */}
            <div className="p-6 rounded-xl bg-white dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700">
              <h3 className="text-sm font-medium text-slate-500 dark:text-slate-400 uppercase tracking-wide mb-4">Details</h3>
              <dl className="space-y-3 text-sm">
                <div className="flex justify-between">
                  <dt className="text-slate-500 dark:text-slate-400">Category</dt>
                  <dd className="text-slate-800 dark:text-slate-200">{template.category}</dd>
                </div>
                <div className="flex justify-between">
                  <dt className="text-slate-500 dark:text-slate-400">Contracts</dt>
                  <dd className="text-slate-800 dark:text-slate-200">{template.contracts.length}</dd>
                </div>
                <div className="flex justify-between">
                  <dt className="text-slate-500 dark:text-slate-400">Prompts</dt>
                  <dd className="text-slate-800 dark:text-slate-200">{template.samplePrompts.length}</dd>
                </div>
                <div className="flex justify-between">
                  <dt className="text-slate-500 dark:text-slate-400">Difficulty</dt>
                  <dd className="capitalize text-slate-800 dark:text-slate-200">{template.difficulty}</dd>
                </div>
              </dl>
            </div>

            {/* Networks */}
            <div className="p-6 rounded-xl bg-white dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700">
              <h3 className="text-sm font-medium text-slate-500 dark:text-slate-400 uppercase tracking-wide mb-4">Networks</h3>
              <div className="flex flex-wrap gap-2">
                {[...new Set(template.contracts.map(c => c.network))].map(networkId => {
                  const network = NETWORKS.find(n => n.id === networkId);
                  return (
                    <div key={networkId} className="flex items-center gap-2 px-3 py-1.5 rounded-full bg-slate-100 dark:bg-slate-900">
                      <span>{network?.icon}</span>
                      <span className="text-sm text-slate-700 dark:text-slate-300">{network?.name || networkId}</span>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}
